version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  

  app:
    image: eoffice:latest
    container_name: eoffice
    depends_on:
      - ollama
    environment:
      - "OPENAI_BASE_URL=http://ollama:11434/v1"
      - "OPENAI_API_KEY=ollama"
      - "OPENAI_MODEL=gemma3:27b" 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  

volumes:
  ollama_data:
